version: 2
updates:
  - package-ecosystem: composer
    directory: /
    open-pull-requests-limit: 25
    schedule:
      interval: daily
                          
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 25
    schedule:
      interval: daily
